// lib/tools-constants.ts
// All string constants for Tools.tsx - kept in a .ts file so the
// SWC JSX parser never sees CSS/HTML strings inside the .tsx component.

export const PRINT_STYLES: string = [
  '@media print {',
  '  @page { size: A4; margin: 12mm 12mm; }',
  '  * { -webkit-print-color-adjust: exact !important; print-color-adjust: exact !important; }',
  '  body * { visibility: hidden !important; }',
  '  #pm-print-zone, #pm-print-zone * { visibility: visible !important; }',
  '  #pm-print-zone {',
  '    position: absolute !important;',
  '    left: 0 !important;',
  '    top: 0 !important;',
  '    width: 100% !important;',
  '    background: white !important;',
  '    padding: 0 !important;',
  '    display: block !important;',
  "    font-family: 'Inter', 'Helvetica', sans-serif !important;",
  '    font-size: 11pt !important;',
  '    line-height: 1.6 !important;',
  '    color: #000 !important;',
  '  }',
  '  .pm-print-container { width: 100%; border-collapse: collapse; table-layout: fixed; }',
  '  .pm-print-container thead { display: table-header-group; }',
  '  .pm-print-header {',
  '    width: 100% !important;',
  '    display: flex !important;',
  '    align-items: center !important;',
  '    justify-content: space-between !important;',
  '    border-bottom: 2pt solid #4f46e5 !important;',
  '    background: white !important;',
  '    padding: 10pt 0 !important;',
  '    margin-bottom: 15pt !important;',
  '  }',
  '  #pm-print-zone h1 { font-size:18pt; font-weight:900; text-transform:uppercase; color:#1e3a5f; margin:20pt 0 10pt; border-bottom:2pt solid #4f46e5; padding-bottom:6pt; page-break-after: avoid; }',
  '  #pm-print-zone h2 { font-size:14pt; font-weight:800; text-transform:uppercase; color:#1e3a5f; margin:24pt 0 8pt; border-bottom:1pt solid #e2e8f0; padding-bottom:4pt; page-break-after: avoid; }',
  '  #pm-print-zone h3 { font-size:12pt; font-weight:800; color:#4f46e5; margin:18pt 0 6pt; page-break-after: avoid; }',
  '  #pm-print-zone p { margin:8pt 0; font-size:11pt; orphans: 3; widows: 3; }',
  '  #pm-print-zone ul, #pm-print-zone ol { margin:8pt 0 8pt 20pt; }',
  '  #pm-print-zone li { margin:4pt 0; font-size:11pt; }',
  '  #pm-print-zone table { width:100%; border-collapse:collapse; margin:12pt 0; font-size:10pt; page-break-inside: auto; table-layout: auto; }',
  '  #pm-print-zone tr { page-break-inside: avoid; page-break-after: auto; }',
  '  #pm-print-zone th { background:#f1f5f9 !important; color:#1e3a5f; font-weight:800; text-transform:uppercase; font-size:9pt; padding:8pt 10pt; border:1pt solid #cbd5e1; }',
  '  #pm-print-zone td { padding:8pt 10pt; border:1pt solid #e2e8f0; vertical-align:top; word-break: break-word; }',
  '  #pm-print-zone div[style*="overflow-x:auto"] { overflow: visible !important; margin: 0 !important; }',
  '  .no-print { display: none !important; }',
  '}',
  '@media screen { .pm-print-header { display: none !important; } }',
].join('\n');
