// lib/tools-constants.ts
// All string constants for Tools.tsx - kept in a .ts file so the
// SWC JSX parser never sees CSS/HTML strings inside the .tsx component.

export const PRINT_STYLES: string = [
  '@media print {',
  '  @page { size: A4; margin: 15mm 15mm; }',
  '  * { -webkit-print-color-adjust: exact !important; print-color-adjust: exact !important; }',
  '  body * { visibility: hidden !important; }',
  '  #pm-print-zone, #pm-print-zone * { visibility: visible !important; }',
  '  #pm-print-zone {',
  '    position: absolute !important;',
  '    left: 0 !important;',
  '    top: 0 !important;',
  '    width: 100% !important;',
  '    background: white !important;',
  '    z-index: 99999 !important;',
  '    padding: 0 !important;',
  '    display: block !important;',
  "    font-family: 'Inter', 'Helvetica', sans-serif !important;",
  '    font-size: 11pt !important;',
  '    line-height: 1.5 !important;',
  '    color: #000 !important;',
  '  }',
  '  .pm-print-container { width: 100%; border-collapse: collapse; }',
  '  .pm-print-header {',
  '    width: 100% !important;',
  '    height: 60px !important;',
  '    display: flex !important;',
  '    align-items: center !important;',
  '    justify-content: space-between !important;',
  '    border-bottom: 1.5pt solid #4f46e5 !important;',
  '    background: white !important;',
  '    padding: 0 5mm !important;',
  '    box-sizing: border-box !important;',
  '    margin-bottom: 10pt !important;',
  '  }',
  '  #pm-print-zone h1 { font-size:16pt; font-weight:900; text-transform:uppercase; color:#1e3a5f; margin:12pt 0 8pt; border-bottom:1.5pt solid #4f46e5; padding-bottom:4pt; }',
  '  #pm-print-zone h2 { font-size:12pt; font-weight:800; text-transform:uppercase; color:#1e3a5f; margin:16pt 0 6pt; border-bottom:0.5pt solid #e2e8f0; padding-bottom:3pt; page-break-after: avoid; }',
  '  #pm-print-zone h3 { font-size:11pt; font-weight:800; color:#4f46e5; margin:12pt 0 4pt; page-break-after: avoid; }',
  '  #pm-print-zone p { margin:6pt 0; font-size:10.5pt; orphans: 3; widows: 3; }',
  '  #pm-print-zone ul, #pm-print-zone ol { margin:6pt 0 6pt 15pt; }',
  '  #pm-print-zone li { margin:3pt 0; font-size:10.5pt; }',
  '  #pm-print-zone table { width:100%; border-collapse:collapse; margin:10pt 0; font-size:9.5pt; page-break-inside: auto; }',
  '  #pm-print-zone tr { page-break-inside: avoid; page-break-after: auto; }',
  '  #pm-print-zone th { background:#f8fafc !important; color:#1e3a5f; font-weight:800; text-transform:uppercase; font-size:8pt; padding:6pt 8pt; border:0.5pt solid #cbd5e1; }',
  '  #pm-print-zone td { padding:6pt 8pt; border:0.5pt solid #e2e8f0; vertical-align:top; }',
  '  .no-print { display: none !important; }',
  '}',
  '@media screen { .pm-print-header { display: none !important; } }',
].join('\n');
